# -*- coding: utf-8 -*-
"""Prompting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WrrddkMLazSyfX7LLEu7SHIs6KTkwHhm
"""

import os
os.remove("fp6_prompts.jsonl")

"""
generate_manifest_fp6.py
--------------------------
Manifest generator for FP6 (Fitzpatrick VI) psoriasis images.
Pulls from the 'psoriasis-only-sorted' GCS bucket using the
stable_diffusion_prompts.csv as an image index.

Outputs: fp6_manifest.csv / fp6_prompts.jsonl / fp6_rejected.jsonl

Usage:
    python3 generate_manifest_fp6.py   # or just run the cell in Colab
"""

import asyncio
import json
import logging
import re
import sys
from datetime import datetime, UTC
from pathlib import Path

import cv2
import numpy as np
import pandas as pd
from google.cloud import storage
from tqdm.asyncio import tqdm_asyncio
from google import genai
from google.genai import types as genai_types
import transformers
import huggingface_hub
transformers.logging.set_verbosity_error()
huggingface_hub.utils.logging.set_verbosity_error()

# ── Config ─────────────────────────────────────────────────────────────────────

PROJECT_ID      = "skin-tone-classifier"
VERTEX_LOCATION = "us-central1"
IMAGE_BUCKET    = "psoriasis-only-sorted"
CSV_INDEX       = "stable_diffusion_prompts.csv"

OUTPUT_MANIFEST = "fp6_manifest.csv"
PROMPTS_CACHE   = "fp6_prompts.jsonl"
REJECTED_LOG    = "fp6_rejected.jsonl"

TARGET_FST      = ["FP6"]
TEST_LIMIT      = 21               # FP6 has 21 images total
VARIANTS_PER    = 1
BASE_SEED       = 42
MAX_CONCURRENT  = 1                # serial execution avoids 429s for small batches

SD_STRENGTH          = 0.30
SD_GUIDANCE_SCALE    = 7.5
SD_CONTROLNET_SCALE  = 0.80
SD_STEPS             = 50

MIN_DIMENSION      = 224
GEMINI_MODEL       = "gemini-2.5-flash"
GEMINI_RESIZE_PX   = 1024
THINKING_BUDGET    = 1024
WATERMARK_CROP_PCT = 0.10

# ── FST descriptions ────────────────────────────────────────────────────────────

FST_DESCRIPTIONS = {
    "FP1": "very fair skin Fitzpatrick I-II",
    "FP2": "fair skin Fitzpatrick II-III",
    "FP3": "medium tan skin Fitzpatrick III-IV",
    "FP4": "medium-dark brown skin Fitzpatrick IV-V",
    "FP5": "dark brown skin Fitzpatrick V-VI",
    "FP6": "deep dark brown skin Fitzpatrick VI",
}

UNIVERSAL_NEGATIVE = (
    "jewelry, rings, watch, bracelet, metal, silver, gold, shiny, blurry, "
    "low resolution, distorted, unnatural colors, deformed anatomy, extra digits, "
    "writing, overlay, text, logo, SFS, watermark"
)

GEMINI_PROMPT = """You are an expert clinical dermatology image analyst assisting with research.

You will receive (a) a dermatology image, (b) the ground-truth disease label from
the dataset, and (c) the disease category. Return ONLY a valid JSON object with
exactly these fields:

{
  "framing_style":     "<lead phrase for the prompt, e.g. 'medical realism close-up of', 'macro clinical photo of', 'clinical photograph of'>",
  "body_part":         "<specific anatomical location, e.g. 'dorsal forearm', 'elbow', 'three fingertips', 'both hands'>",
  "primary_lesion":    "<primary lesion morphology, e.g. 'multiple well-circumscribed thickened plaques', 'coalescing plaques'>",
  "lesion_color":      "<precise color of the lesion itself, e.g. 'dusky red-violet', 'deep orange-red', 'reddish-violet'>",
  "scale_detail":      "<rich scale description, e.g. 'silvery-white micaceous scale', 'thick adherent micaceous silvery scale', 'yellowish-brown hyperkeratotic scales', 'none'>",
  "secondary_changes": "<clinically notable co-occurring details, e.g. 'shallow fissures within scale', 'post-inflammatory hyperpigmentation at lesion edges', 'natural body hair growing through lesions', 'subungual hyperkeratosis, nail pitting, onycholysis'>",
  "distribution":      "<spatial pattern, e.g. 'covering knuckles and fingers', 'large map-like areas', 'island in a sea pattern'>",
  "background_detail": "<any contextual detail that grounds realism, e.g. 'white fabric background', 'direct clear clinical lighting', 'none'>"
}

How to fill each field:

1. VISUAL EVIDENCE FIRST. Describe exactly what you see in the image. Be
   specific and concrete — vague terms like "lesion present" are useless.

2. USE THE DISEASE LABEL AS A CLINICAL PRIOR. For fields that are ambiguous
   or partially obscured, fall back on textbook morphology for that disease.
   Example: psoriasis -> scale_detail should be "silvery-white micaceous scale"
   even if scale is partly obscured.

3. framing_style sets the opening phrase of the final SD prompt. Match the
   actual image framing: use "macro clinical photo of" for extreme close-ups,
   "dorsal view of" for orientation-led shots, "medical realism close-up of"
   as the general default.

4. scale_detail must be RICH and SPECIFIC. This is the most important visual
   discriminator for many conditions. Good examples:
     - "silvery-white micaceous scale"
     - "thick adherent yellowish-brown hyperkeratotic scale"
     - "fine powdery white scale"
     - "none" (only if the disease genuinely has no scale)

5. secondary_changes should capture co-occurring clinical details that add
   realism: fissures, PIH, nail changes, hair growing through lesions,
   excoriation marks, lichenification. List 1-3 items separated by commas.

6. NEVER return null, "unclear", "not visible", or "unknown". Always commit
   to a specific clinical description.

7. Do NOT describe skin color or Fitzpatrick tone -- that is provided separately.

8. Return ONLY the JSON object -- no explanation, no markdown fences.

9. BREVITY IS CRITICAL. Each field value must be 6 words or fewer.
   Rank information density over completeness -- pick the single most
   discriminating descriptor per field. Long values will be truncated
   and lose their end, which is worse than being concise upfront.
"""

SLOT_FALLBACKS = {
    "framing_style":     "medical realism close-up of",
    "body_part":         "skin surface",
    "primary_lesion":    "skin lesion",
    "lesion_color":      "erythematous",
    "scale_detail":      "surface scale present",
    "secondary_changes": "surface changes present",
    "distribution":      "present on skin",
    "background_detail": "none",
}

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)


# ── CSV-based image index loader ──────────────────────────────────────────────────

def load_dataset_items() -> pd.DataFrame:
    log.info(f"Loading image index from {CSV_INDEX}...")
    df = pd.read_csv(CSV_INDEX)

    df["blob_name"]     = df["file_url"].str.replace(f"gs://{IMAGE_BUCKET}/", "", regex=False)
    df["md5hash"]       = df["blob_name"].apply(lambda p: Path(p).stem)
    df["fst_class"]     = df["fitzpatrick_scale"].apply(lambda x: f"FP{int(x)}")
    df["disease_label"] = "psoriasis"
    df["disease_group"] = "inflammatory skin disease"
    df["partition"]     = "TRAIN"

    # Drop the generic pre-existing prompts -- Gemini generates the real ones
    df = df.drop(columns=["sd_prompt", "fitzpatrick_scale", "file_url"])

    log.info(f"Loaded {len(df)} images total")
    log.info(dict(df["fst_class"].value_counts().sort_index()))
    return df


# ── GCS download ──────────────────────────────────────────────────────────────────

def download_image_bytes(blob_name: str) -> bytes | None:
    try:
        gcs_client = storage.Client(project=PROJECT_ID)
        bucket     = gcs_client.bucket(IMAGE_BUCKET)
        return bucket.blob(blob_name).download_as_bytes()
    except Exception as e:
        log.warning(f"GCS download failed for {blob_name}: {e}")
        return None


# ── Image preprocessing ───────────────────────────────────────────────────────────

def crop_watermark(img: np.ndarray) -> np.ndarray:
    h = img.shape[0]
    return img[:int(h * (1 - WATERMARK_CROP_PCT)), :]


def qc_source_image(img_bgr: np.ndarray) -> tuple[bool, str]:
    h, w = img_bgr.shape[:2]
    if min(h, w) < MIN_DIMENSION:
        return False, f"too_small_{w}x{h}"
    return True, "passed"


def resize_for_gemini(img_bgr: np.ndarray) -> np.ndarray:
    h, w  = img_bgr.shape[:2]
    scale = GEMINI_RESIZE_PX / max(h, w)
    if scale >= 1.0:
        return img_bgr
    return cv2.resize(img_bgr, (int(w * scale), int(h * scale)), interpolation=cv2.INTER_AREA)


# ── Gemini Vision call ────────────────────────────────────────────────────────────

async def call_gemini(
    client: genai.Client,
    img_bytes: bytes,
    disease: str,
    disease_group: str,
    md5hash: str,
    sem: asyncio.Semaphore,
) -> dict | None:
    async with sem:
        for attempt in range(4):
            try:
                text_part = (
                    f"Disease label (ground truth): {disease}\n"
                    f"Disease category (ground truth): {disease_group}\n\n"
                    + GEMINI_PROMPT
                )
                loop     = asyncio.get_event_loop()
                response = await loop.run_in_executor(
                    None,
                    lambda: client.models.generate_content(
                        model=GEMINI_MODEL,
                        contents=[
                            genai_types.Part.from_bytes(data=img_bytes, mime_type="image/jpeg"),
                            text_part,
                        ],
                        config=genai_types.GenerateContentConfig(
                            temperature=0.0,
                            max_output_tokens=1500,
                            thinking_config=genai_types.ThinkingConfig(
                                thinking_budget=THINKING_BUDGET
                            ),
                        ),
                    )
                )
                raw = response.text.strip()
                if raw.startswith("```"):
                    parts = raw.split("```")
                    raw   = parts[1] if len(parts) > 1 else raw
                    if raw.startswith("json"):
                        raw = raw[4:]
                return json.loads(raw.strip())
            except json.JSONDecodeError as e:
                log.warning(f"JSON parse error {md5hash} attempt {attempt+1}: {e}")
                if attempt == 3:
                    return None
            except Exception as e:
                log.warning(f"Gemini API error {md5hash} attempt {attempt+1}: {e}")
                if attempt == 3:
                    return None
                # Exponential backoff: 60s, 120s, 240s — or use Retry-After if provided
                match = re.search(r'retry in (\d+(?:\.\d+)?)s', str(e), re.IGNORECASE)
                wait  = float(match.group(1)) + 5 if match else 60 * (2 ** attempt)
                log.info(f"Rate limited. Waiting {wait:.0f}s before attempt {attempt+2}...")
                await asyncio.sleep(wait)
    return None


# ── Prompt assembly ───────────────────────────────────────────────────────────────

def get_slot(gemini_json: dict, key: str) -> str:
    val = gemini_json.get(key)
    return str(val) if val else SLOT_FALLBACKS[key]


_clip_tok = None

def _get_clip_tokenizer():
    global _clip_tok
    if _clip_tok is None:
        from transformers import CLIPTokenizer
        _clip_tok = CLIPTokenizer.from_pretrained("openai/clip-vit-base-patch32")
    return _clip_tok


def clip_truncate(prompt: str, max_tokens: int = 75) -> str:
    """Truncate to SD 1.5's real CLIP token budget (77 total - 2 special tokens)."""
    tok = _get_clip_tokenizer()
    ids = tok.encode(prompt, add_special_tokens=False)
    if len(ids) <= max_tokens:
        return prompt
    log.warning(f"Prompt {len(ids)} tokens > {max_tokens}, truncating")
    truncated  = tok.decode(ids[:max_tokens]).strip()
    last_comma = truncated.rfind(",")
    return truncated[:last_comma].strip() if last_comma > 0 else truncated


def assemble_negative(gemini_json: dict, disease: str) -> str:
    per_image: list[str] = ["healthy skin", "smooth skin", "clear skin"]

    body = gemini_json.get("body_part", "").lower()

    if any(x in body for x in ("hand", "finger", "palm", "digit")):
        per_image += ["extra fingers", "deformed hand", "single hand"]
    if any(x in body for x in ("face", "cheek", "forehead", "nose")):
        per_image += ["makeup", "cosmetics", "beauty filter"]
    if any(x in body for x in ("leg", "foot", "ankle", "toe")):
        per_image += ["extra toes", "deformed foot"]
    if any(x in body for x in ("nail", "fingernail", "toenail")):
        per_image += ["nail polish", "artificial nails"]
    if any(x in body for x in ("scalp", "hair")):
        per_image += ["wig", "hat", "hair product"]
    if any(x in body for x in ("genital", "vulva", "groin", "pubic", "perineal")):
        per_image += ["clothing", "underwear", "fabric covering"]

    d = disease.lower()

    if "psoriasis" in d:
        per_image += ["scale-free skin", "smooth plaque"]
    if any(x in d for x in ("ulcer", "ulcerated", "neutrophilic", "pyoderma")):
        per_image += ["intact skin", "unbroken skin", "healed wound"]
    if any(x in d for x in ("nematode", "parasite", "larva", "helminth", "worm")):
        per_image += ["insect", "spider bite", "bee sting"]
    if any(x in d for x in ("carcinoma", "melanoma", "cancer", "scc", "bcc")):
        per_image += ["benign lesion", "normal mole", "freckle"]
    if "lupus" in d:
        per_image += ["normal skin", "no rash"]
    if any(x in d for x in ("sun damage", "actinic", "photoaging")):
        per_image += ["youthful skin", "smooth unwrinkled skin"]
    if "vitiligo" in d:
        per_image += ["uniform pigmentation", "even skin tone"]
    if any(x in d for x in ("eczema", "dermatitis", "atopic")):
        per_image += ["non-inflamed skin", "dry scale-free skin"]

    scale = gemini_json.get("scale_detail", "").lower()
    if any(x in scale for x in ("none", "no scale", "absent")):
        per_image += ["scale", "scaly surface", "peeling skin"]

    # FP6-specific: prevent desaturated/ashy rendering of dark skin
    if "FP6" in str(gemini_json.get("fst_class", "")) or True:
        per_image += ["ashy skin", "grayish skin tone", "desaturated skin", "washed out complexion"]

    return UNIVERSAL_NEGATIVE + ", " + ", ".join(per_image)


def assemble_prompt(gemini_json: dict, disease: str, fst_class: str) -> str:
    """
    Assembles the SD prompt. background_detail is dropped to save tokens,
    and secondary_changes is capped to the first item only.
    Most prompts were hitting 80-111 tokens before these changes.
    """
    skin_desc = FST_DESCRIPTIONS[fst_class]

    framing   = get_slot(gemini_json, "framing_style")
    body      = get_slot(gemini_json, "body_part")
    color     = get_slot(gemini_json, "lesion_color")
    lesion    = get_slot(gemini_json, "primary_lesion")
    scale     = get_slot(gemini_json, "scale_detail")
    secondary = get_slot(gemini_json, "secondary_changes").split(",")[0].strip()
    dist      = get_slot(gemini_json, "distribution")
    # background_detail intentionally dropped -- saves ~5-10 tokens

    # SD pays most attention to early tokens — lead with lesion color+type,
    # then scale (key psoriasis discriminator), then distribution, then secondary
    prompt = (
        f"{framing} {body} on {skin_desc}, "
        f"{color} {lesion}, "
        f"{scale}, "
        f"{dist}, "
        f"{secondary}"
    )
    return clip_truncate(prompt.replace("\n", " "))


# ── Per-image processing ──────────────────────────────────────────────────────────

async def process_image(
    row: dict,
    client: genai.Client,
    sem: asyncio.Semaphore,
    cache: dict,
    rejected: list,
    cache_lock: asyncio.Lock,
) -> list[dict] | None:

    md5hash     = row["md5hash"]
    blob_name   = row["blob_name"]
    fst_class   = row.get("fst_class", "UNKNOWN")
    disease     = row.get("disease_label", "psoriasis")
    disease_grp = row.get("disease_group", "inflammatory skin disease")
    partition   = row.get("partition", "TRAIN")
    source_uri  = f"gs://{IMAGE_BUCKET}/{blob_name}"

    loop      = asyncio.get_event_loop()
    raw_bytes = await loop.run_in_executor(
        None, download_image_bytes, blob_name
    )
    if raw_bytes is None:
        rejected.append({"md5hash": md5hash, "blob_name": blob_name, "reason": "gcs_download_failed"})
        return None

    img_arr = np.frombuffer(raw_bytes, dtype=np.uint8)
    img_bgr = cv2.imdecode(img_arr, cv2.IMREAD_COLOR)
    if img_bgr is None:
        rejected.append({"md5hash": md5hash, "reason": "decode_failed"})
        return None

    img_bgr        = crop_watermark(img_bgr)
    h, w           = img_bgr.shape[:2]
    passed, reason = qc_source_image(img_bgr)
    if not passed:
        rejected.append({"md5hash": md5hash, "fst_class": fst_class, "reason": reason})
        return None

    if md5hash in cache:
        gemini_json = cache[md5hash]
    else:
        resized_bgr   = resize_for_gemini(img_bgr)
        _, buf        = cv2.imencode(".jpg", resized_bgr, [cv2.IMWRITE_JPEG_QUALITY, 90])
        resized_bytes = buf.tobytes()

        gemini_json = await call_gemini(
            client, resized_bytes, disease, disease_grp, md5hash, sem
        )
        if gemini_json is None:
            rejected.append({"md5hash": md5hash, "reason": "gemini_api_failed"})
            return None
        cache[md5hash] = gemini_json
        async with cache_lock:
            with open(PROMPTS_CACHE, "a") as f:
                f.write(json.dumps({"md5hash": md5hash, **gemini_json}) + "\n")

    prompt = assemble_prompt(gemini_json, disease, fst_class)

    rows = []
    for v in range(VARIANTS_PER):
        seed = BASE_SEED + (hash(md5hash) % 10000) + v
        rows.append({
            "md5hash":             md5hash,
            "fst_class":           fst_class,
            "disease_label":       disease,
            "disease_group":       disease_grp,
            "partition":           partition,
            "variant_index":       v,
            "source_gcs_uri":      source_uri,
            "synthetic_gcs_uri":   f"gs://fp17kc-synthetic/{fst_class}/{md5hash}_v{v}.jpg",
            "assembled_prompt":    prompt,
            "negative_prompt":     assemble_negative(gemini_json, disease),
            "framing_style":       get_slot(gemini_json, "framing_style"),
            "body_part":           get_slot(gemini_json, "body_part"),
            "primary_lesion":      get_slot(gemini_json, "primary_lesion"),
            "lesion_color":        get_slot(gemini_json, "lesion_color"),
            "scale_detail":        get_slot(gemini_json, "scale_detail"),
            "secondary_changes":   get_slot(gemini_json, "secondary_changes"),
            "distribution":        get_slot(gemini_json, "distribution"),
            "background_detail":   get_slot(gemini_json, "background_detail"),
            "vision_model":        GEMINI_MODEL,
            "watermark_cropped":   True,
            "source_width":        w,
            "source_height":       h,
            "source_passed_qc":    True,
            "strength":            SD_STRENGTH,
            "guidance_scale":      SD_GUIDANCE_SCALE,
            "controlnet_scale":    SD_CONTROLNET_SCALE,
            "steps":               SD_STEPS,
            "seed":                seed,
            "output_laplacian":    None,
            "output_ssim":         None,
            "output_skin_ratio":   None,
            "passed_qc":           None,
            "rejection_reason":    None,
            "automl_split":        "TRAIN",
            "generated_at":        None,
            "pipeline_version":    "v1.0",
            "manifest_created_at": datetime.now(UTC).isoformat(),
        })
    return rows


# ── Main ─────────────────────────────────────────────────────────────────────────

async def main():
    log.info("=== Fitzpatrick Manifest Generator -- FP6 ===")
    log.info(f"Project:        {PROJECT_ID}")
    log.info(f"Bucket:         gs://{IMAGE_BUCKET}/")
    log.info(f"Vision model:   {GEMINI_MODEL}")
    log.info(f"Target:         {TEST_LIMIT} FP6 images")

    # ── Authentication ────────────────────────────────────────────────────────
    if "ipykernel" in sys.modules:
        try:
            from google.colab import auth as colab_auth
            colab_auth.authenticate_user()
            log.info("Colab authentication completed")
        except ImportError:
            # Plain Jupyter -- run: gcloud auth application-default login
            log.info("Not in Colab -- using Application Default Credentials")
    # ─────────────────────────────────────────────────────────────────────────

    client = genai.Client(
        vertexai=True,
        project=PROJECT_ID,
        location=VERTEX_LOCATION,
    )
    log.info(f"Vertex AI client initialized ({PROJECT_ID} / {VERTEX_LOCATION})")

    df          = load_dataset_items()
    df_filtered = df[df["fst_class"].isin(TARGET_FST)].copy()
    df_test     = df_filtered.head(TEST_LIMIT).reset_index(drop=True)

    log.info(f"FP6 images to process: {len(df_test)}")

    Path(PROMPTS_CACHE).touch(exist_ok=True)
    cache = {}
    with open(PROMPTS_CACHE) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
                cache[entry["md5hash"]] = {k: v for k, v in entry.items() if k != "md5hash"}
            except json.JSONDecodeError:
                log.warning(f"Skipping malformed cache line: {line[:80]}")
    log.info(f"Loaded {len(cache)} cached Gemini responses")

    sem        = asyncio.Semaphore(MAX_CONCURRENT)
    cache_lock = asyncio.Lock()
    rejected   = []

    tasks = [
        process_image(row.to_dict(), client, sem, cache, rejected, cache_lock)
        for _, row in df_test.iterrows()
    ]

    results = await tqdm_asyncio.gather(*tasks, desc="FP6 run")

    all_rows = [r for result in results if result for r in result]

    if all_rows:
        manifest_df = pd.DataFrame(all_rows)
        manifest_df.to_csv(OUTPUT_MANIFEST, index=False)
        log.info(f"\nManifest saved: {OUTPUT_MANIFEST}")
        log.info(f"  Rows:           {len(manifest_df)}")
        log.info(f"  Unique sources: {manifest_df['md5hash'].nunique()}")
        log.info(f"\nSample prompt:\n  {manifest_df['assembled_prompt'].iloc[0]}")
    else:
        log.warning("No rows generated -- check fp6_rejected.jsonl")

    if rejected:
        with open(REJECTED_LOG, "w") as f:
            for entry in rejected:
                f.write(json.dumps(entry) + "\n")
        log.info(f"Rejected: {len(rejected)} -- see {REJECTED_LOG}")


if __name__ == "__main__":
    if "ipykernel" in sys.modules:
        await main()
    else:
        asyncio.run(main())

import pandas as pd, json

# How many rows?
df = pd.read_csv("fp6_manifest.csv")
print(len(df), "rows")

# Any new rejections?
with open("fp6_rejected.jsonl") as f:
    for line in f:
        print(json.loads(line))